### ISSUE TITLE
Excuse me, where is the database?

### ISSUE THREAD

**Issue by rogersisci** [poria72/Persian-Document-Management-System---Laravel#1]
Excuse me, where is the database?

**Comment by poria72** [comment]
The database will be created using artisan commands. Please follow the steps:
Copy & setup .env file
Create database & Change DB_DATABASE in .env
Migrate the Database: php artisan migrate

**Comment by poria72** [comment]
> 
> 
> Excuse me, where is the database?

The database will be created using artisan commands. Please follow the steps:
Copy & setup .env file
Create database & Change DB_DATABASE in .env
Migrate the Database: php artisan migrate
